---
name: CI
on: [push]
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version:
        - 3.11
        edx_branch:
        - master
        - open-release/redwood.master
        - open-release/sumac.master
          # Add more branches as needed

    steps:
    - uses: actions/checkout@v4

    - name: Set up python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
        cache: 'pip' # Cache pip dependencies

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install build tool and dependencies
      run: |
        # Install the build tool
        uv pip install --system build
        # Install dev dependencies defined in the root pyproject.toml (if any)
        # uv pip sync --dev # Uncomment if you have [tool.uv.dev-dependencies]

    - name: Build all packages
      run: |
        # Iterate through workspace members and build each one
        # Extract members from root pyproject.toml (requires toml parser like yq or similar, or hardcode)
        # For simplicity, listing them explicitly based on pyproject.toml:
        PACKAGES=(
            "src/edx_sysadmin"
            "src/edx_username_changer"
            "src/ol_openedx_canvas_integration"
            "src/ol_openedx_chat"
            "src/ol_openedx_checkout_external"
            "src/ol_openedx_course_export"
            "src/ol_openedx_course_structure_api"
            "src/ol_openedx_git_auto_export"
            "src/ol_openedx_logging"
            "src/ol_openedx_otel_monitoring"
            "src/ol_openedx_rapid_response_reports"
            "src/ol_openedx_sentry"
            "src/ol_social_auth"
            "src/openedx_companion_auth"
            "src/rapid_response_xblock"
        )
        for pkg_dir in "${PACKAGES[@]}"; do
          echo "Building $pkg_dir..."
          python -m build "$pkg_dir"
        done

    - name: Install tutor
      run: |
        if [[ "${{ matrix.edx_branch }}" == "open-release/redwood.master" ]]; then
          uv pip install --system tutor==18.2.2
        elif [[ "${{ matrix.edx_branch }}" == "master" ]]; then
          git clone --branch=main https://github.com/overhangio/tutor.git
          uv pip install --system -e "./tutor"
        else
          uv pip install --system tutor==19.0.0
        fi

    - name: Set up tutor with edx-platform
      run: |
        cd ..
        git clone https://github.com/openedx/edx-platform
        cd edx-platform
        git checkout ${{ matrix.edx_branch }}
        tutor mounts add .
        tutor dev launch --non-interactive
        tutor dev stop

    - name: Run tests on tutor
      run: |
        if [[ "${{ matrix.edx_branch }}" == "master" ]]; then
          DIRECTORY="tutor-main"
          DEV="tutor_main_dev"
        else
          DIRECTORY="tutor"
          DEV="tutor_dev"
        fi
        EDX_WORKSPACE=$PWD/.. docker compose -f /home/runner/.local/share/$DIRECTORY/env/local/docker-compose.yml -f /home/runner/.local/share/$DIRECTORY/env/dev/docker-compose.yml --project-name $DEV run -v $PWD/../open-edx-plugins:/openedx/open-edx-plugins lms /openedx/open-edx-plugins/run_edx_integration_tests.sh

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
